name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Explicit MSTest
      run: |
        cp tests/UnitTestEx.Api/bin/Debug/netcoreapp3.1/UnitTestEx.Api.deps.json tests/UnitTestEx.MSTest.Test/bin/Debug/netcoreapp3.1
        cd tests/UnitTestEx.MSTest.Test/bin/Debug/netcoreapp3.1
        dotnet test UnitTestEx.MSTest.Test.dll --no-build --verbosity normal