name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test MSTest
      run: |
        cd tests/UnitTestEx.MSTest.Test/bin/debug/netcoreapp3.1
        ls
        cd tests/UnitTestEx.MSTest.Test
        dotnet test --no-build --verbosity normal